version: 2
jobs:
  build:
    docker:
      - image: golang:1.11rc2
    steps:
      - checkout
      - run: go version
      - run: go env
      - run: test -z "$(find -name '*.go' | tee /dev/stdout | xargs gofmt -l)"
      - run: go build -v .
      - run: go test -v ./...
      - run: go vet ./...
